{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "victoria-frontend.serviceAccountName" . }}
  labels:
    {{- include "victoria-frontend.labels" . | nindent 4 }}
{{- end -}}
